image: blurri/meteor-node

variables:
  METEOR_ALLOW_SUPERUSER: 'true'

cache:
  paths:
    - 'node_modules'
    - '.meteor'

stages:
  - test

# https://gitlab.com/gitlab-org/gitlab-runner/issues/327#note_3346917
before_script:
  - [ -f  /cache/.meteor ] && mv /cache/.meteor ~/.meteor
  - [ -f  /cache/.npm ] && mv /cache/.npm ~/.npm
  - ./install_meteor.sh
  - meteor npm i

unit:
  stage: test
  script:
    - echo "Logged!"

after_script:
  - [ -f  ~/.meteor ] && mv ~/.meteor /cache/.meteor
  - [ -f  ~/.npm ] && mv ~/.npm /cache/.npm
