image: blurri/meteor-node

variables:
  METEOR_ALLOW_SUPERUSER: 'true'

cache:
  paths:
    - 'node_modules'
    - '.meteor'

stages:
  - test

# https://gitlab.com/gitlab-org/gitlab-runner/issues/327#note_3346917
before_script:
  - ./restore_caches.sh
  - ./install_meteor.sh
  - meteor npm i

unit:
  stage: test
  script:
    - echo "Logged!"

after_script:
  - ./store_caches.sh
