image: blurri/meteor-node

variables:
  METEOR_ALLOW_SUPERUSER: 'true'

cache:
  paths:
    - 'node_modules'
    - '.meteor'
    - '.npm'
    - '.meteorInstall'

stages:
  - test

before_script:
  - mv .meteorInstall ~/.meteor
  - mv .npm ~/.npm
  - ./install_meteor.sh
  - meteor npm i

after_script:
  - mv ~/.meteor .meteorInstall
  - mv ~/.npm .npm

unit:
  stage: test
  script:
    - echo "Logged!"
