image: blurri/meteor-node

variables:
  METEOR_ALLOW_SUPERUSER: 'true'

cache:
  paths:
    - 'node_modules'
    - '.meteor'

stages:
  - test

before_script:
  - mv /cache/.meteor ~/.meteor
  - mv /cache/.npm ~/.npm
  - ./install_meteor.sh
  - meteor npm i

after_script:
  - mv ~/.meteor /cache/.meteor
  - mv ~/.npm /cache/.npm

unit:
  stage: test
  script:
    - echo "Logged!"
