image: blurri/meteor-node

variables:
  METEOR_ALLOW_SUPERUSER: 'true'

cache:
  paths:
    - 'node_modules'
    - '.meteor'
    - '~/.npm'
    - '~/.meteor'
    - '~/meteor'

stages:
  - test

before_script:
  - ./install_meteor.sh
  - meteor npm i
  - cd ~
  - ls -al

unit:
  stage: test
  script:
    - meteor npm t
