image: node:8.11.4

variables:
  METEOR_ALLOW_SUPERUSER: 'true'

cache:
  paths:
    - 'node_modules'
    - '.meteor'
    - '~/.npm'
    - '~/.meteor'
    - '~/meteor'

stages:
  - test

before_script:
  - curl "https://install.meteor.com?release=1.7.0.5" | /bin/sh
  - meteor npm i

unit_tests:
  stage: test
  script:
    - meteor npm t
